// Shared constants across the application

// Countries sorted alphabetically by name
export const countries = [
  { code: 'GB', name: 'Anglia', flag: '/img/flag/gb.svg' },
  { code: 'AT', name: 'Austria', flag: '/img/flag/at.svg' },
  { code: 'BE', name: 'Belgia', flag: '/img/flag/be.svg' },
  { code: 'DK', name: 'Danemarca', flag: '/img/flag/dk.svg' },
  { code: 'FI', name: 'Finlanda', flag: '/img/flag/fi.svg' },
  { code: 'FR', name: 'Franța', flag: '/img/flag/fr.svg' },
  { code: 'DE', name: 'Germania', flag: '/img/flag/de.svg' },
  { code: 'GR', name: 'Grecia', flag: '/img/flag/gr.svg' },
  { code: 'IE', name: 'Irlanda', flag: '/img/flag/ie.svg' },
  { code: 'NIR', name: 'Irlanda de Nord', flag: '/img/flag/nir.svg' },
  { code: 'IT', name: 'Italia', flag: '/img/flag/it.svg' },
  { code: 'MD', name: 'Moldova', flag: '/img/flag/md.svg' },
  { code: 'NO', name: 'Norvegia', flag: '/img/flag/no.svg' },
  { code: 'NL', name: 'Olanda', flag: '/img/flag/nl.svg' },
  { code: 'PT', name: 'Portugalia', flag: '/img/flag/pt.svg' },
  { code: 'RO', name: 'România', flag: '/img/flag/ro.svg' },
  { code: 'SC', name: 'Scoția', flag: '/img/flag/sc.svg' },
  { code: 'ES', name: 'Spania', flag: '/img/flag/es.svg' },
  { code: 'SE', name: 'Suedia', flag: '/img/flag/se.svg' },
  { code: 'WLS', name: 'Țara Galilor', flag: '/img/flag/wls.svg' },
];

// Simple countries list (without flag) for forms
export const countriesSimple = countries.map(({ code, name }) => ({ code, name }));

// Județe/Regions by country - Full list for all countries
export const judetByCountry: Record<string, string[]> = {
  RO: ["Alba", "Arad", "Argeș", "Bacău", "Bihor", "Bistrița-Năsăud", "Botoșani", "Brașov", "Brăila", "București", "Buzău", "Călărași", "Caraș-Severin", "Cluj", "Constanța", "Covasna", "Dâmbovița", "Dolj", "Galați", "Giurgiu", "Gorj", "Harghita", "Hunedoara", "Ialomița", "Iași", "Ilfov", "Maramureș", "Mehedinți", "Mureș", "Neamț", "Olt", "Prahova", "Sălaj", "Satu Mare", "Sibiu", "Suceava", "Teleorman", "Timiș", "Tulcea", "Vaslui", "Vâlcea", "Vrancea"],
  GB: ["Bedfordshire", "Berkshire", "Bristol", "Buckinghamshire", "Cambridgeshire", "Cheshire", "Cornwall", "County Durham", "Cumbria", "Derbyshire", "Devon", "Dorset", "East Riding of Yorkshire", "East Sussex", "Essex", "Gloucestershire", "Greater London", "Greater Manchester", "Hampshire", "Herefordshire", "Hertfordshire", "Isle of Wight", "Kent", "Lancashire", "Leicestershire", "Lincolnshire", "Londra", "Merseyside", "Norfolk", "North Yorkshire", "Northamptonshire", "Northumberland", "Nottinghamshire", "Oxfordshire", "Rutland", "Shropshire", "Somerset", "South Yorkshire", "Staffordshire", "Suffolk", "Surrey", "Tyne and Wear", "Warwickshire", "West Midlands", "West Sussex", "West Yorkshire", "Wiltshire", "Worcestershire"],
  IT: ["Abruzzo", "Basilicata", "Calabria", "Campania", "Emilia-Romagna", "Friuli-Venezia Giulia", "Lazio", "Liguria", "Lombardia", "Marche", "Molise", "Piemonte", "Puglia", "Sardegna", "Sicilia", "Toscana", "Trentino-Alto Adige", "Umbria", "Valle d'Aosta", "Veneto"],
  ES: ["Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country", "Canary Islands", "Cantabria", "Castile and León", "Castilla-La Mancha", "Catalonia", "Extremadura", "Galicia", "La Rioja", "Madrid", "Murcia", "Navarre", "Valencia"],
  DE: ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"],
  FR: ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur"],
  AT: ["Burgenland", "Carinthia", "Lower Austria", "Salzburg", "Styria", "Tyrol", "Upper Austria", "Vienna", "Vorarlberg"],
  BE: ["Antwerp", "Brussels", "East Flanders", "Flemish Brabant", "Hainaut", "Liège", "Limburg", "Luxembourg", "Namur", "Walloon Brabant", "West Flanders"],
  NL: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland"],
  GR: ["Attica", "Central Greece", "Central Macedonia", "Crete", "East Macedonia and Thrace", "Epirus", "Ionian Islands", "North Aegean", "Peloponnese", "South Aegean", "Thessaly", "Western Greece", "Western Macedonia"],
  PT: ["Aveiro", "Azores", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisbon", "Madeira", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu"],
  NO: ["Agder", "Innlandet", "Møre og Romsdal", "Nordland", "Oslo", "Rogaland", "Troms og Finnmark", "Trøndelag", "Vestfold og Telemark", "Vestland", "Viken"],
  SE: ["Blekinge", "Dalarna", "Gotland", "Gävleborg", "Halland", "Jämtland", "Jönköping", "Kalmar", "Kronoberg", "Norrbotten", "Skåne", "Stockholm", "Södermanland", "Uppsala", "Värmland", "Västerbotten", "Västernorrland", "Västmanland", "Västra Götaland", "Örebro", "Östergötland"],
  DK: ["Capital Region", "Central Denmark Region", "North Denmark Region", "Region Zealand", "Region of Southern Denmark"],
  FI: ["Central Finland", "Central Ostrobothnia", "Etelä-Savo", "Kainuu", "Kanta-Häme", "Kymenlaakso", "Lapland", "North Karelia", "North Ostrobothnia", "North Savo", "Ostrobothnia", "Pirkanmaa", "Päijät-Häme", "Satakunta", "South Karelia", "South Ostrobothnia", "Uusimaa", "Varsinais-Suomi", "Åland"],
  IE: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"],
  NIR: ["Antrim", "Armagh", "Down", "Fermanagh", "Londonderry", "Tyrone"],
  SC: ["Aberdeenshire", "Angus", "Argyll and Bute", "City of Edinburgh", "Clackmannanshire", "Dumfries and Galloway", "Dundee City", "East Ayrshire", "East Dunbartonshire", "East Lothian", "East Renfrewshire", "Falkirk", "Fife", "Glasgow City", "Highland", "Inverclyde", "Midlothian", "Moray", "North Ayrshire", "North Lanarkshire", "Orkney Islands", "Perth and Kinross", "Renfrewshire", "Scottish Borders", "Shetland Islands", "South Ayrshire", "South Lanarkshire", "Stirling", "West Dunbartonshire", "West Lothian", "Western Isles"],
  WLS: ["Anglesey", "Blaenau Gwent", "Bridgend", "Caerphilly", "Cardiff", "Carmarthenshire", "Ceredigion", "Conwy", "Denbighshire", "Flintshire", "Gwynedd", "Merthyr Tydfil", "Monmouthshire", "Neath Port Talbot", "Newport", "Pembrokeshire", "Powys", "Rhondda Cynon Taf", "Swansea", "Torfaen", "Vale of Glamorgan", "Wrexham"],
  MD: ["Anenii Noi", "Bălți", "Basarabeasca", "Bender", "Briceni", "Cahul", "Călărași", "Cantemir", "Căușeni", "Chișinău", "Cimișlia", "Criuleni", "Dondușeni", "Drochia", "Dubăsari", "Edineț", "Fălești", "Florești", "Glodeni", "Hîncești", "Ialoveni", "Leova", "Nisporeni", "Ocnița", "Orhei", "Rezina", "Rîșcani", "Sîngerei", "Soroca", "Strășeni", "Șoldănești", "Ștefan Vodă", "Taraclia", "Telenești", "Ungheni"],
};

// Service Types - Unified definition across the app
// Note: Icons are rendered in components, not stored here
export const serviceTypes = [
  { 
    id: 'colete', 
    value: 'Colete',
    name: 'Transport Colete', 
    label: 'Colete & Pachete',
    description: 'Colete și pachete standard',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/20',
    borderColor: 'border-blue-500/30',
    gradient: 'from-orange-500 to-orange-600',
  },
  { 
    id: 'plicuri', 
    value: 'Plicuri',
    name: 'Transport Plicuri/Documente', 
    label: 'Plicuri & Documente',
    description: 'Documente și plicuri urgente',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/20',
    borderColor: 'border-yellow-500/30',
    gradient: 'from-yellow-500 to-orange-500',
  },
  { 
    id: 'persoane', 
    value: 'Persoane',
    name: 'Transport Persoane', 
    label: 'Transport Persoane',
    description: 'Pasageri - călătorii în România și Europa',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/20',
    borderColor: 'border-pink-500/30',
    gradient: 'from-pink-500 to-rose-500',
  },
  { 
    id: 'electronice', 
    value: 'Electronice',
    name: 'Transport Electronice', 
    label: 'Electronice',
    description: 'Echipamente electronice fragile',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/20',
    borderColor: 'border-purple-500/30',
    gradient: 'from-purple-500 to-indigo-500',
  },
  { 
    id: 'animale', 
    value: 'Animale',
    name: 'Transport Animale', 
    label: 'Animale de Companie',
    description: 'Transport animale de companie',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/20',
    borderColor: 'border-emerald-500/30',
    gradient: 'from-emerald-500 to-teal-500',
  },
  { 
    id: 'platforma', 
    value: 'Platforma',
    name: 'Transport cu Platformă', 
    label: 'Transport Platformă',
    description: 'Vehicule și echipamente grele',
    color: 'text-red-400',
    bgColor: 'bg-red-500/20',
    borderColor: 'border-red-500/30',
    gradient: 'from-orange-500 to-amber-500',
  },
  { 
    id: 'tractari', 
    value: 'Tractari',
    name: 'Tractări Auto', 
    label: 'Tractări Auto',
    description: 'Tractări și asistență rutieră',
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/20',
    borderColor: 'border-orange-500/30',
    gradient: 'from-orange-500 to-orange-600',
  },
  { 
    id: 'mobila', 
    value: 'Mobila',
    name: 'Transport Mobilă', 
    label: 'Mobilă & Mutări',
    description: 'Mobilier și obiecte voluminoase',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/20',
    borderColor: 'border-amber-500/30',
    gradient: 'from-amber-500 to-yellow-500',
  },
  { 
    id: 'paleti', 
    value: 'Paleti',
    name: 'Transport Paleți', 
    label: 'Paleți & Marfă',
    description: 'Transport paleți și marfă paletizată',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/20',
    borderColor: 'border-cyan-500/30',
    gradient: 'from-cyan-500 to-blue-500',
  },
];

// Service Names Map - for display
export const serviceNames: Record<string, string> = {
  colete: 'Transport Colete',
  plicuri: 'Transport Plicuri',
  mobila: 'Transport Mobilă',
  electronice: 'Transport Electronice',
  animale: 'Transport Animale',
  persoane: 'Transport Persoane',
  platforma: 'Transport Platformă',
  tractari: 'Tractări Auto',
  paleti: 'Transport Paleți',
};

// Order Status Configurations - Unified across client and courier dashboards
export const orderStatusConfig = {
  noua: {
    label: 'Nouă',
    shortLabel: 'Nouă',
    color: 'text-white',
    bg: 'bg-white/10',
    border: 'border-white/20',
    dotColor: 'bg-white',
    canEdit: true,
    canDelete: true,
  },
  in_lucru: {
    label: 'În Lucru',
    shortLabel: 'În Lucru',
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
    dotColor: 'bg-orange-400',
    canEdit: false,
    canDelete: false,
  },
  acceptata: {
    label: 'Acceptată',
    shortLabel: 'Acceptată',
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    dotColor: 'bg-blue-400',
    canEdit: false,
    canDelete: false,
  },
  in_tranzit: {
    label: 'În tranzit',
    shortLabel: 'În Tranzit',
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
    dotColor: 'bg-orange-400',
    canEdit: false,
    canDelete: false,
  },
  livrata: {
    label: 'Finalizată',
    shortLabel: 'Livrată',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    dotColor: 'bg-emerald-400',
    canEdit: false,
    canDelete: false,
  },
  anulata: {
    label: 'Anulată',
    shortLabel: 'Anulată',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/20',
    dotColor: 'bg-yellow-400',
    canEdit: false,
    canDelete: false,
  },
  // Old English statuses (for backwards compatibility)
  pending: {
    label: 'Nouă',
    shortLabel: 'Nouă',
    color: 'text-white',
    bg: 'bg-white/10',
    border: 'border-white/20',
    dotColor: 'bg-white',
    canEdit: true,
    canDelete: true,
  },
  accepted: {
    label: 'Acceptată',
    shortLabel: 'Acceptată',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/20',
    dotColor: 'bg-yellow-400',
    canEdit: false,
    canDelete: false,
  },
  in_transit: {
    label: 'În tranzit',
    shortLabel: 'În Tranzit',
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/20',
    dotColor: 'bg-orange-400',
    canEdit: false,
    canDelete: false,
  },
  completed: {
    label: 'Finalizată',
    shortLabel: 'Livrată',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    dotColor: 'bg-emerald-400',
    canEdit: false,
    canDelete: false,
  },
  cancelled: {
    label: 'Anulată',
    shortLabel: 'Anulată',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/20',
    dotColor: 'bg-yellow-400',
    canEdit: false,
    canDelete: false,
  },
};
