// Mock orders for testing - one for each service type

export const mockOrders = [
  {
    id: 'mock-order-1',
    orderNumber: 141121,
    clientName: 'Ion Popescu',
    clientPhone: '+40721234567',
    expeditorTara: 'România',
    expeditorJudet: 'București',
    oras_ridicare: 'București',
    destinatarTara: 'Germania',
    destinatarJudet: 'Berlin',
    oras_livrare: 'Berlin',
    tipColet: 'colete',
    greutate: 15,
    status: 'noua' as const,
    dataColectare: '2025-12-15',
    pret: 250,
    createdAt: new Date('2025-12-13T10:30:00'),
    valoare_marfa: '500',
    optiuni: ['asigurare', 'tracking'],
    observatii: 'Fragil - manipulare cu grijă'
  },
  {
    id: 'mock-order-2',
    orderNumber: 141122,
    clientName: 'Maria Ionescu',
    clientPhone: '+40722345678',
    expeditorTara: 'România',
    expeditorJudet: 'Cluj',
    oras_ridicare: 'Cluj-Napoca',
    destinatarTara: 'Franța',
    destinatarJudet: 'Paris',
    oras_livrare: 'Paris',
    tipColet: 'plicuri',
    greutate: 2,
    status: 'noua' as const,
    dataColectare: '2025-12-14',
    pret: 80,
    createdAt: new Date('2025-12-13T11:15:00'),
    optiuni: ['semnatura'],
    observatii: 'Documente importante - livrare rapidă'
  },
  {
    id: 'mock-order-3',
    orderNumber: 141123,
    clientName: 'Andrei Vasilescu',
    clientPhone: '+40723456789',
    expeditorTara: 'România',
    expeditorJudet: 'Timișoara',
    oras_ridicare: 'Timișoara',
    destinatarTara: 'Italia',
    destinatarJudet: 'Milano',
    oras_livrare: 'Milano',
    tipColet: 'mobila',
    greutate: 250,
    status: 'noua' as const,
    dataColectare: '2025-12-16',
    pret: 850,
    createdAt: new Date('2025-12-13T09:45:00'),
    valoare_marfa: '3000',
    optiuni: ['asigurare', 'tracking'],
    observatii: 'Mobilier fragil - necesită protecție suplimentară'
  },
  {
    id: 'mock-order-4',
    orderNumber: 141124,
    clientName: 'Elena Georgescu',
    clientPhone: '+40724567890',
    expeditorTara: 'România',
    expeditorJudet: 'Iași',
    oras_ridicare: 'Iași',
    destinatarTara: 'Spania',
    destinatarJudet: 'Madrid',
    oras_livrare: 'Madrid',
    tipColet: 'electronice',
    greutate: 8,
    status: 'noua' as const,
    dataColectare: '2025-12-17',
    pret: 180,
    createdAt: new Date('2025-12-13T14:20:00'),
    valoare_marfa: '1200',
    optiuni: ['asigurare', 'tracking', 'semnatura'],
    observatii: 'Laptop și accesorii - foarte fragil'
  },
  {
    id: 'mock-order-5',
    orderNumber: 141125,
    clientName: 'Cristian Popa',
    clientPhone: '+40725678901',
    expeditorTara: 'România',
    expeditorJudet: 'Brașov',
    oras_ridicare: 'Brașov',
    destinatarTara: 'Austria',
    destinatarJudet: 'Viena',
    oras_livrare: 'Viena',
    tipColet: 'animale',
    greutate: 12,
    status: 'noua' as const,
    dataColectare: '2025-12-15',
    pret: 320,
    createdAt: new Date('2025-12-13T08:30:00'),
    optiuni: ['tracking'],
    observatii: 'Pisică - necesită manipulare delicată și pauze regulate'
  },
  {
    id: 'mock-order-6',
    orderNumber: 141126,
    clientName: 'Mihai Constantin',
    clientPhone: '+40726789012',
    expeditorTara: 'România',
    expeditorJudet: 'Constanța',
    oras_ridicare: 'Constanța',
    destinatarTara: 'Belgia',
    destinatarJudet: 'Brussels',
    oras_livrare: 'Brussels',
    tipColet: 'platforma',
    greutate: 800,
    status: 'noua' as const,
    dataColectare: '2025-12-18',
    pret: 1200,
    createdAt: new Date('2025-12-13T13:45:00'),
    valoare_marfa: '5000',
    optiuni: ['asigurare', 'tracking'],
    observatii: 'Utilaje industriale - transport pe platformă'
  },
  {
    id: 'mock-order-7',
    orderNumber: 141127,
    clientName: 'Alexandra Dumitrescu',
    clientPhone: '+40727890123',
    expeditorTara: 'România',
    expeditorJudet: 'Sibiu',
    oras_ridicare: 'Sibiu',
    destinatarTara: 'Olanda',
    destinatarJudet: 'Amsterdam',
    oras_livrare: 'Amsterdam',
    tipColet: 'tractari',
    greutate: 1500,
    status: 'noua' as const,
    dataColectare: '2025-12-19',
    pret: 950,
    createdAt: new Date('2025-12-13T15:10:00'),
    valoare_marfa: '8000',
    optiuni: ['asigurare', 'tracking'],
    observatii: 'Autovehicul defect - tractare necesară'
  },
  {
    id: 'mock-order-8',
    orderNumber: 141128,
    clientName: 'Florin Stanescu',
    clientPhone: '+40728901234',
    expeditorTara: 'gb',
    expeditorJudet: 'London',
    oras_ridicare: 'London',
    destinatarTara: 'România',
    destinatarJudet: 'București',
    oras_livrare: 'București',
    tipColet: 'aeroport',
    greutate: 3,
    status: 'noua' as const,
    dataColectare: 'Flexibil',
    pret: 150,
    createdAt: new Date('2025-12-13T07:20:00'),
    observatii: 'Transfer de la Heathrow la hotel în centrul Bucureștiului'
  },
  {
    id: 'mock-order-9',
    orderNumber: 141129,
    clientName: 'Diana Marinescu',
    clientPhone: '+40729012345',
    expeditorTara: 'România',
    expeditorJudet: 'Ploiești',
    oras_ridicare: 'Ploiești',
    destinatarTara: 'Germania',
    destinatarJudet: 'München',
    oras_livrare: 'München',
    tipColet: 'persoane',
    greutate: 0,
    status: 'noua' as const,
    dataColectare: '2025-12-20',
    pret: 280,
    createdAt: new Date('2025-12-13T16:30:00'),
    observatii: '3 persoane - călătorie cu bagaje'
  },
  {
    id: 'mock-order-10',
    orderNumber: 141130,
    clientName: 'Vasile Radu',
    clientPhone: '+40720123456',
    expeditorTara: 'România',
    expeditorJudet: 'Galați',
    oras_ridicare: 'Galați',
    destinatarTara: 'Grecia',
    destinatarJudet: 'Atena',
    oras_livrare: 'Atena',
    tipColet: 'paleti',
    greutate: 450,
    status: 'noua' as const,
    dataColectare: '2025-12-21',
    pret: 680,
    createdAt: new Date('2025-12-13T12:00:00'),
    valoare_marfa: '4500',
    optiuni: ['asigurare', 'tracking'],
    observatii: '6 paleți de mărfuri - necesită încărcare cu stivuitor'
  }
];

// Helper function to add mock orders to the list (for testing UI)
export const getMockOrdersForService = (serviciu: string) => {
  return mockOrders.filter(order => order.tipColet.toLowerCase() === serviciu.toLowerCase());
};

// Get all mock orders
export const getAllMockOrders = () => mockOrders;

// Get mock order by ID
export const getMockOrderById = (id: string) => {
  return mockOrders.find(order => order.id === id);
};
