import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import LayoutWrapper from "@/components/LayoutWrapper";
import { GoogleAnalytics } from "@/components/GoogleAnalytics";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  metadataBase: new URL('https://curierulperfect.com'),
  title: {
    default: "Curierul Perfect - Transport România Europa",
    template: "%s | Curierul Perfect"
  },
  description: "Platformă de transport național și european: colete, plicuri, persoane, mobilă, electronice, animale, platformă auto și tractări. Servicii rapide și sigure în România și Europa. Conectă-te cu curieri verificați.",
  verification: {
    google: 'bXTrL9PuFBb8dmi7E5pUmCszVdmkf0vD4COmHxHJJaY',
  },
  keywords: [
    "transport național România",
    "transport colete Europa",
    "curier România Europa",
    "transport persoane Europa",
    "transport mobilă Europa",
    "transport național și internațional",
    "livrări naționale",
    "transport electronice",
    "transport animale de companie",
    "platformă auto Europa",
    "tractări auto internaționale",
    "transport plicuri documente",
    "curierat european",
    "trimite colete Germania",
    "trimite colete Anglia",
    "trimite colete Italia",
    "trimite colete Spania",
    "marketplace curierat",
    "transport România",
  ],
  authors: [{ name: "Curierul Perfect" }],
  creator: "Curierul Perfect",
  publisher: "Curierul Perfect",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "Transport Colete România Europa | Curierul Perfect",
    description: "Trimite colete, mobilă, animale sau transportă persoane România-Europa. Curieri verificați. UK, Germania, Italia, Spania.",
    type: "website",
    locale: "ro_RO",
    url: "https://curierulperfect.com",
    siteName: "Curierul Perfect",
    // OG image is auto-generated by opengraph-image.tsx
  },
  facebook: {
    appId: '1020128696638498',
  },
  twitter: {
    card: "summary_large_image",
    title: "Curierul Perfect - Transport Complet în Europa",
    description: "Platformă curierat european: transport colete, plicuri, persoane, mobilă, electronice, animale și mai mult.",
    // Twitter image is auto-generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  alternates: {
    canonical: "https://curierulperfect.com",
    languages: {
      'ro-RO': 'https://curierulperfect.com',
    },
  },
  category: "transport",
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icon.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: [
      { url: '/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    shortcut: '/favicon.ico',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f97316' },
    { media: '(prefers-color-scheme: dark)', color: '#0f172a' },
  ],
};

// JSON-LD Structured Data - Organization + WebSite
const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': 'https://curierulperfect.com/#organization',
  name: 'Curierul Perfect',
  url: 'https://curierulperfect.com',
  logo: {
    '@type': 'ImageObject',
    url: 'https://curierulperfect.com/icon.png',
    width: 512,
    height: 512,
  },
  description: 'Platformă curierat european: transport colete, plicuri, persoane, mobilă, electronice, animale, platformă auto și tractări între România și Europa.',
  foundingDate: '2024',
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer service',
    email: 'contact@curierulperfect.com',
    availableLanguage: ['Romanian', 'English'],
  },
  sameAs: [
    'https://www.facebook.com/curierulperfect',
  ],
  address: {
    '@type': 'PostalAddress',
    addressCountry: 'RO',
  },
  areaServed: [
    { '@type': 'Country', name: 'Romania' },
    { '@type': 'Country', name: 'Germany' },
    { '@type': 'Country', name: 'United Kingdom' },
    { '@type': 'Country', name: 'Italy' },
    { '@type': 'Country', name: 'Spain' },
    { '@type': 'Country', name: 'France' },
    { '@type': 'Country', name: 'Austria' },
    { '@type': 'Country', name: 'Belgium' },
    { '@type': 'Country', name: 'Netherlands' },
  ],
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Servicii de Transport',
    itemListElement: [
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Transport colete', url: 'https://curierulperfect.com/servicii/colete' } },
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Transport persoane', url: 'https://curierulperfect.com/servicii/persoane' } },
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Transport mobilă', url: 'https://curierulperfect.com/servicii/mobila' } },
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Transport animale', url: 'https://curierulperfect.com/servicii/animale' } },
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Platformă auto', url: 'https://curierulperfect.com/servicii/platforma' } },
      { '@type': 'Offer', itemOffered: { '@type': 'Service', name: 'Transport electronice', url: 'https://curierulperfect.com/servicii/electronice' } },
    ],
  },
};

const webSiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': 'https://curierulperfect.com/#website',
  url: 'https://curierulperfect.com',
  name: 'Curierul Perfect',
  description: 'Platformă de transport național și european pentru România',
  publisher: {
    '@id': 'https://curierulperfect.com/#organization',
  },
  inLanguage: 'ro-RO',
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: 'https://curierulperfect.com/servicii?q={search_term_string}',
    },
    'query-input': 'required name=search_term_string',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ro" data-scroll-behavior="smooth">
      <head>
        {/* Preconnect to Firebase for faster auth/db connections */}
        <link rel="preconnect" href="https://firebasestorage.googleapis.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.googleapis.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://identitytoolkit.googleapis.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://firebasestorage.googleapis.com" />
        <link rel="dns-prefetch" href="https://identitytoolkit.googleapis.com" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteSchema) }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <GoogleAnalytics />
        <AuthProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </AuthProvider>
        <Toaster 
          position="top-right"
          toastOptions={{
            style: {
              background: 'rgba(30, 41, 59, 0.95)',
              color: 'white',
              border: '1px solid rgba(255, 255, 255, 0.1)',
              backdropFilter: 'blur(12px)',
            },
            className: 'sonner-toast',
          }}
        />
      </body>
    </html>
  );
}
